#!/usr/bin/python

Import("env")

if env["tools"]:
    env.tests_sources = []
    env.add_source_files(env.tests_sources, "*.cpp")

    lib = env.add_library("tests", env.tests_sources)
    env.Prepend(LIBS=[lib])
