#!/usr/bin/env python

Import("env")

# Third-party code

third_party_obj = []

third_party_sources = "#third-party/misc/mikktspace.c"

env_third_party = env.Clone()
env_third_party.disable_warnings()
env_third_party.add_source_files(third_party_obj, third_party_sources)
env.scene_sources += third_party_obj

# Rebel source files

scene_obj = []

env.add_source_files(scene_obj, "*.cpp")
env.scene_sources += scene_obj

# Needed to force rebuilding the scene files when the third-party code is updated.
env.Depends(scene_obj, third_party_obj)

SConscript("default_theme/SCsub")
