#!/usr/bin/env bash

# git pre-commit hook that runs a clang-format style check.

# The application and options.
application="clang-format"
options="--Wno-error=unknown"

# File extensions to parse.
include_extensions=".c .h .cpp .hpp .cc .hh .cxx .m .mm .inc .java .glsl"

# Directories and file patterns to ignore.
exclude_directories="thirdparty platform/android/project/engine/src/com/google"
exclude_file_patterns="\-so_wrap\."

# To get consistent formatting, use the same clang-format version as CI.
recommended_clang_format_major_min="14"
recommended_clang_format_major_max="17"

# Determine the major version of clang-format being used.
# The returned string can be inconsistent depending on where clang-format comes from.
# Example output strings reported by `clang-format --version`:
# - Ubuntu: "Ubuntu clang-format version 11.0.0-2"
# - Fedora: "clang-format version 11.0.0 (Fedora 11.0.0-2.fc33)"
clang_format_version="$(clang-format --version | sed "s/[^0-9\.]*\([0-9\.]*\).*/\1/")"
clang_format_major_version="$(echo "$clang_format_version" | cut -d. -f1)"

if [[ "$clang_format_major_version" -lt "$recommended_clang_format_major_min" ]]; then
    echo "Warning: Your version of clang-format is $clang_format_version."
    echo "The minimum recommended version of clang-format is $recommended_clang_format_major_min."
    echo "Consider upgrading clang-format as formatting may not be applied correctly."
fi

if [[ "$clang_format_major_version" -gt "$recommended_clang_format_major_max" ]]; then
    echo "Warning: Your version of clang-format is $clang_format_version."
    echo "The maximum recommended version of clang-format is $recommended_clang_format_major_max."
    echo "Consider downgrading clang-format as formatting may not be applied correctly."
fi

. "$(dirname -- "$0")/pre-commit-style-check" \
    "$application"                            \
    "$options"                                \
    "$include_files"                          \
    "$include_extensions"                     \
    "$exclude_directories"                    \
    "$exclude_file_patterns"                  \
