#!/usr/bin/env python

Import("env")
Import("env_modules")

env_mbed_tls = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []

if env["builtin_mbedtls"]:
    thirdparty_sources = [
        "aes.c",
        "aesce.c",
        "aesni.c",
        "aria.c",
        "asn1parse.c",
        "asn1write.c",
        "base64.c",
        "bignum.c",
        "bignum_core.c",
        "bignum_mod.c",
        "bignum_mod_raw.c",
        "block_cipher.c",
        "camellia.c",
        "ccm.c",
        "chacha20.c",
        "chachapoly.c",
        "cipher.c",
        "cipher_wrap.c",
        "cmac.c",
        "constant_time.c",
        "ctr_drbg.c",
        "debug.c",
        "des.c",
        "dhm.c",
        "ecdh.c",
        "ecdsa.c",
        "ecjpake.c",
        "ecp.c",
        "ecp_curves.c",
        "ecp_curves_new.c",
        "entropy.c",
        "entropy_poll.c",
        "error.c",
        "gcm.c",
        "hkdf.c",
        "hmac_drbg.c",
        "lmots.c",
        "lms.c",
        "md5.c",
        "md.c",
        "memory_buffer_alloc.c",
        "mps_reader.c",
        "mps_trace.c",
        "net_sockets.c",
        "nist_kw.c",
        "oid.c",
        "padlock.c",
        "pem.c",
        "pk.c",
        "pkcs12.c",
        "pkcs5.c",
        "pkcs7.c",
        "pk_ecc.c",
        "pkparse.c",
        "pk_wrap.c",
        "pkwrite.c",
        "platform.c",
        "platform_util.c",
        "poly1305.c",
        "psa_crypto_aead.c",
        "psa_crypto.c",
        "psa_crypto_cipher.c",
        "psa_crypto_client.c",
        "psa_crypto_driver_wrappers_no_static.c",
        "psa_crypto_ecp.c",
        "psa_crypto_ffdh.c",
        "psa_crypto_hash.c",
        "psa_crypto_mac.c",
        "psa_crypto_pake.c",
        "psa_crypto_rsa.c",
        "psa_crypto_se.c",
        "psa_crypto_slot_management.c",
        "psa_crypto_storage.c",
        "psa_its_file.c",
        "psa_util.c",
        "ripemd160.c",
        "rsa_alt_helpers.c",
        "rsa.c",
        "sha1.c",
        "sha256.c",
        "sha3.c",
        "sha512.c",
        "ssl_cache.c",
        "ssl_ciphersuites.c",
        "ssl_client.c",
        "ssl_cookie.c",
        "ssl_debug_helpers_generated.c",
        "ssl_msg.c",
        "ssl_ticket.c",
        "ssl_tls12_client.c",
        "ssl_tls12_server.c",
        "ssl_tls13_client.c",
        "ssl_tls13_generic.c",
        "ssl_tls13_keys.c",
        "ssl_tls13_server.c",
        "ssl_tls.c",
        "threading.c",
        "timing.c",
        "version.c",
        "version_features.c",
        "x509.c",
        "x509_create.c",
        "x509_crl.c",
        "x509_crt.c",
        "x509_csr.c",
        "x509write.c",
        "x509write_crt.c",
        "x509write_csr.c",
    ]

    thirdparty_dir = "#thirdparty/mbedtls/library/"
    thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

    env_mbed_tls.Prepend(CPPPATH=["#thirdparty/mbedtls/include/"])

    env_thirdparty = env_mbed_tls.Clone()
    env_thirdparty.disable_warnings()
    env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
    env.modules_sources += thirdparty_obj


# Rebel source files

module_obj = []

env_mbed_tls.add_source_files(module_obj, "*.cpp")

env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
