#!/usr/bin/env bash

# git pre-commit hook that runs a black Python style check.

# The application and options.
application="black"
options=""

# Files and file extensions to parse.
include_files="SConstruct SCsub"
include_extensions=".py"

# Directories to ignore.
exclude_directories="thirdparty"

. "$(dirname -- "$0")/pre-commit-style-check" \
    "$application"                            \
    "$options"                                \
    "$include_files"                          \
    "$include_extensions"                     \
    "$exclude_directories"                    \
    "$exclude_file_patterns"                  \
