#!/usr/bin/env python

import sys

Import("env")

common_server = [
    "os_server.cpp",
]

if sys.platform == "darwin":
    common_server.append("#platform/macos/macos_crash_handler.mm")
    common_server.append("#platform/macos/macos_power.cpp")
else:
    common_server.append("#platform/x11/crash_handler_x11.cpp")
    common_server.append("#platform/x11/power_x11.cpp")

prog = env.add_program("#bin/rebel_server", ["server_main.cpp"] + common_server)
