#!/usr/bin/env python

Import("env")
Import("env_modules")

env_vhacd = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []

thirdparty_dir = "#thirdparty/vhacd/"

env_vhacd.Prepend(CPPPATH=[thirdparty_dir + "include"])

# Godot source files

module_obj = []

env_vhacd.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
