#!/usr/bin/env python

Import("env")
Import("env_modules")

env_vhacd = env_modules.Clone()

# Third-party source files

third_party_obj = []

third_party_dir = "#third-party/vhacd/"

env_vhacd.Prepend(CPPPATH=[third_party_dir + "include"])

# Rebel source files

module_obj = []

env_vhacd.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the third-party library is updated.
env.Depends(module_obj, third_party_obj)
