#!/usr/bin/env python

Import("env")

env.editor_sources = []

import os
import glob
from platform_methods import run_in_subprocess
from compat import open_utf8
import editor_builders


def _make_modules_classes_docs_path(to_path):
    # NOTE: It is safe to generate this file here, since this is still executed serially
    g = open_utf8(os.path.join(to_path, "modules_classes_docs_path.gen.h"), "w")
    g.write(
        "static const int _modules_classes_docs_path_count = "
        + str(len(env.modules_classes_docs_path))
        + ";\n"
    )
    g.write("struct ModulesClassesDocsPath { const char* name; const char* path; };\n")

    g.write(
        "static const ModulesClassesDocsPath _modules_classes_docs_path["
        + str(len(env.modules_classes_docs_path) + 1)
        + "] = {\n"
    )
    for name in sorted(env.modules_classes_docs_path):
        g.write(
            '    {"' + name + '", "' + env.modules_classes_docs_path[name] + '"},\n'
        )
    g.write("    {NULL, NULL}\n")
    g.write("};\n")
    g.close()


if env["tools"]:
    # Register exporters
    reg_exporters_inc = '#include "register_exporters.h"\n'
    reg_exporters = "void register_exporters() {\n"
    for e in env.platform_exporters:
        # Glob all .cpp files in export folder
        files = Glob("#platforms/" + e + "/export/" + "*.cpp")
        env.add_source_files(env.editor_sources, files)

        reg_exporters += "\tregister_" + e + "_exporter();\n"
        reg_exporters_inc += '#include "platforms/' + e + '/export/export.h"\n'
    reg_exporters += "}\n"

    # NOTE: It is safe to generate this file here, since this is still executed serially
    with open_utf8("register_exporters.gen.cpp", "w") as f:
        f.write(reg_exporters_inc)
        f.write(reg_exporters)

    # Core API documentation.
    docs = []
    docs += Glob("#docs/*.xml")

    # Module API documentation.
    module_dirs = []
    for d in env.modules_classes_docs_path.values():
        if d not in module_dirs:
            module_dirs.append(d)

    for d in module_dirs:
        if not os.path.isabs(d):
            docs += Glob("#" + d + "/*.xml")  # Built-in.
        else:
            docs += Glob(d + "/*.xml")  # Custom.

    _make_modules_classes_docs_path(env.Dir("#editor/docs").abspath)

    docs = sorted(docs)
    env.Depends("#editor/docs_data_compressed.gen.h", docs)
    env.CommandNoCache(
        "#editor/docs_data_compressed.gen.h",
        docs,
        run_in_subprocess(editor_builders.make_docs_header),
    )

    # Rebel Editor and Rebel Engine API translations that are over 90% complete
    # are included in the Rebel Editor build.

    # Editor translations
    to_include = [
        "ar",  # Arabic
        "ca",  # Catalan
        "cs",  # Czech
        "de",  # German
        "el",  # Greek
        "es_AR",  # Spanish (Argentina)
        "es",  # Spanish
        "fi",  # Finnish
        "fr",  # French
        "id",  # Indonesian
        "it",  # Italian
        "ja",  # Japanese
        "ko",  # Korean
        "nl",  # Dutch
        "pl",  # Polish
        "pt_BR",  # Portuguese (Brazil)
        "pt",  # Portuguese
        "ru",  # Russian
        "sr_Cyrl",  # Serbian (cyrillic)
        "th",  # Thai
        "tr",  # Turkish
        "uk",  # Ukrainian
        "zh_CN",  # Chinese (Simplified)
        "zh_TW",  # Chinese (Taiwan)
    ]
    tlist = [
        env.Dir("#editor/translations").abspath + "/" + f + ".po" for f in to_include
    ]
    env.Depends("#editor/editor_translations.gen.h", tlist)
    env.CommandNoCache(
        "#editor/editor_translations.gen.h",
        tlist,
        run_in_subprocess(editor_builders.make_editor_translations_header),
    )

    # Rebel Engine API translations
    to_include = ["es", "ta", "zh_CN"]  # Spanish, Tamil and Chinese (Simplified)
    tlist = [env.Dir("#translations").abspath + "/" + f + ".po" for f in to_include]
    env.Depends("#editor/docs_translations.gen.h", tlist)
    env.CommandNoCache(
        "#editor/docs_translations.gen.h",
        tlist,
        run_in_subprocess(editor_builders.make_docs_translations_header),
    )

    # Fonts
    fonts = glob.glob(env.Dir("#third-party").abspath + "/fonts/*.ttf")
    fonts.sort()
    env.Depends("#editor/builtin_fonts.gen.h", fonts)
    env.CommandNoCache(
        "#editor/builtin_fonts.gen.h",
        fonts,
        run_in_subprocess(editor_builders.make_fonts_header),
    )

    env.add_source_files(env.editor_sources, "*.cpp")
    env.add_source_files(env.editor_sources, "register_exporters.gen.cpp")

    SConscript("collada/SCsub")
    SConscript("docs/SCsub")
    SConscript("fileserver/SCsub")
    SConscript("icons/SCsub")
    SConscript("import/SCsub")
    SConscript("plugins/SCsub")

    lib = env.add_library("editor", env.editor_sources)
    env.Prepend(LIBS=[lib])
