#!/usr/bin/env python

Import("env")
Import("env_modules")

env_stb_vorbis = env_modules.Clone()

# Third-party source files

third_party_obj = []

third_party_sources = ["#third-party/misc/stb_vorbis.c"]

env_third_party = env_stb_vorbis.Clone()
env_third_party.disable_warnings()
env_third_party.add_source_files(third_party_obj, third_party_sources)
env.modules_sources += third_party_obj

# Rebel source files

module_obj = []

env_stb_vorbis.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the third-party library is updated.
env.Depends(module_obj, third_party_obj)
