#!/usr/bin/env python

Import("env")

files = [
    "#platform/windows/windows_dir_access.cpp",
    "#platform/windows/windows_file_access.cpp",
    "#platform/windows/windows_key_mapping.cpp",
    "#platform/windows/windows_terminal_logger.cpp",
    "joypad_uwp.cpp",
    "power_uwp.cpp",
    "context_egl_uwp.cpp",
    "app.cpp",
    "os_uwp.cpp",
]

if "build_angle" in env and env["build_angle"]:
    cmd = env.AlwaysBuild(env.ANGLE("libANGLE.lib", None))

prog = env.add_program("#bin/rebel", files)

if "build_angle" in env and env["build_angle"]:
    env.Depends(prog, [cmd])
