name: 🍎 macOS Builds
on: [push, pull_request]

# Global Settings
env:
  BRANCH_NAME: main
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build-macos:
    runs-on: "macos-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=release_debug, tools=yes)
            cache-name: macos-editor
            target: release_debug
            tools: true
            bin: "./bin/rebel.macos.opt.tools.64"

          - name: Template (target=release, tools=no)
            cache-name: macos-template
            target: release
            tools: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup build cache
        uses: ./.github/actions/build-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup build dependencies
        uses: ./.github/actions/build-dependencies

      - name: Build
        uses: ./.github/actions/build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: macos
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
