name: ☁ Server Builds
on: [push, pull_request]

# Global Settings
env:
  BRANCH_NAME: main
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no module_mono_enabled=yes mono_static=yes mono_glue=no

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-server
  cancel-in-progress: true

jobs:
  build-server:
    runs-on: "ubuntu-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux Headless w/ Mono (target=release_debug, tools=yes)
            cache-name: server-editor-mono
            target: release_debug
            tools: true

          - name: Linux Server w/ Mono (target=release, tools=no)
            cache-name: server-template-mono
            target: release
            tools: false

    steps:
      - uses: actions/checkout@v4

      - name: Linux dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install \
            libasound2-dev \
            libdbus-1-dev \
            libgl1-mesa-dev \
            libglu-dev \
            libx11-dev \
            libxcursor-dev \
            libxi-dev \
            libxinerama-dev \
            libxrandr-dev \
            libpulse-dev \
            libudev-dev \
            mono-devel \
            yasm

      - name: Setup build cache
        uses: ./.github/actions/build-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup build dependencies
        uses: ./.github/actions/build-dependencies

      - name: Build
        uses: ./.github/actions/build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: server
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}
